version: 1.0.{build}

install:
- nuget restore

build:
project: demo\demo.sln
verbosity: detailed

environment:
COVERALLS_REPO_TOKEN:
secure: /c+daHvNZPlD7EhcJ7JpXzqzsMc/x05XfeZiBVsDhmWAbL/UufIhTtKYnerwB5IO

after_test:
# generate report for MSTest testing framework:
- demo\packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:Demo\LogicaDeNegocio.UnitTests\bin\Debug\LogicaDeNegocio.UnitTests.dll" -output:coverage.xml

- demo\packages\coveralls.io.1.1.86\tools\coveralls.net.exe --opencover coverage.xml